name: Lint and Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 mypy black isort pydocstyle vulture pyright

      - name: Run flake8
        run: flake8 app/

      - name: Run mypy
        run: mypy app/

      - name: Run black
        run: black --check app/

      - name: Run isort
        run: isort --check-only app/

      - name: Run pydocstyle
        run: pydocstyle app/

      - name: Run vulture
        run: vulture app/ --min-confidence 80

      - name: Run pyright
        run: pyright app/ 