name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  security-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit bandit
      
      - name: Check Python dependencies for vulnerabilities
        run: |
          pip-audit --json --output pip-audit-report.json || true
      
      - name: Run Bandit static analysis
        run: |
          bandit -r app/ --format json --output bandit-report.json || true
      
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            pip-audit-report.json
            bandit-report.json

  security-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: portal/pnpm-lock.yaml
      
      - name: Install dependencies
        run: |
          cd portal
          pnpm install --frozen-lockfile
      
      - name: Run npm audit
        run: |
          cd portal
          pnpm audit --audit-level=moderate || true
      
      - name: Run npm outdated check
        run: |
          cd portal
          pnpm outdated || true 