name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: pytest --cov=app --cov=tests --cov-report=xml --cov-report=term
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: portal/pnpm-lock.yaml
      - name: Install dependencies
        run: |
          cd portal
          pnpm install --frozen-lockfile
      - name: Run TypeScript type checking
        run: |
          cd portal
          pnpm exec tsc --noEmit
      - name: Run frontend tests
        run: |
          cd portal
          pnpm exec vitest run
      - name: Run frontend tests with coverage
        run: |
          cd portal
          pnpm exec vitest run --coverage
      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: portal/coverage/
      - name: Run frontend linting
        run: |
          cd portal
          pnpm run lint 