name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Download NLTK VADER lexicon
        run: python -m nltk.downloader vader_lexicon
      - name: Run tests with coverage
        run: pytest --cov=app --cov=tests --cov-report=xml --cov-report=term
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  test-frontend:
    runs-on: ubuntu-latest
    # Set a default working directory for all run steps in this job
    defaults:
      run:
        working-directory: ./portal
    steps:
      - uses: actions/checkout@v4
      
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache-dependency-path: portal/pnpm-lock.yaml
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run TypeScript type checking
        run: pnpm exec tsc --noEmit
      - name: Run frontend tests
        run: pnpm exec vitest run
      - name: Run frontend tests with coverage
        run: pnpm exec vitest run --coverage
      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: portal/coverage/
      - name: Run frontend linting
        run: pnpm run lint